export const EXTENSION_PATHS = {
  IGNORE_TYPES: "src/ignore-types.list",
  TEMPLATES_LIST: "src/templates.list",
  TEMPLATES_FOLDER: "src/toptal/templates",
} as const;

export const MESSAGES = {
  EXTENSION_ACTIVATED:
    'Congratulations, your extension "Ignore Generator" is now active!',
  NO_TEMPLATES: "No templates found!",
  OPEN_WORKSPACE_FIRST: "Please open a workspace first!",
  FILE_CREATED_SUCCESS: (fileName: string, templateCount: number) =>
    `${fileName} created successfully with ${templateCount} template(s)!`,
  TEMPLATES_APPENDED: (templateCount: number) =>
    `Added ${templateCount} template(s) to existing ignore file!`,
  FILE_EXISTS_WARNING: (fileName: string) =>
    `${fileName} already exists. What would you like to do?`,
  ERROR_PREFIX: "Error: ",
} as const;

export const UI_PLACEHOLDERS = {
  SELECT_IGNORE_TYPE: "Select the type of ignore file to create",
  SELECT_TEMPLATES: "Select templates to include (you can select multiple)",
} as const;

export const COMMENT_TEMPLATES = {
  HEADER: (fileName: string) =>
    `# ${fileName} file generated by VS Code Ignore Extension`,
  TIMESTAMP: () => `# Generated on: ${new Date().toISOString()}`,
  APPEND_TIMESTAMP: () => `# ===== Added on ${new Date().toISOString()} =====`,
  TEMPLATE_SECTION: (templateName: string) => `### ${templateName} ###`,
  STACK_SECTION: (stackName: string) => `### ${stackName} Stack ###`,
  PATCH_SECTION: (templateName: string) => `### ${templateName} Patch ###`,
  TEMPLATE_NOT_FOUND: (templateName: string) =>
    `# Template ${templateName} not found`,
} as const;
